num_repetitions: 3
T:
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10

target_budget:
  - 10000
  - 10500
  - 11000
  - 11500
  - 12000
  - 12500
  - 13000
  - 10000
  - 10500
  - 11000
  - 11500
  - 12000
  - 12500
  - 13000
  - 10000
  - 10500
  - 11000
  - 11500
  - 12000
  - 12500
  - 13000

dataset: pascal
train_config: train_configGP.yml
cost_seg-cls:
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12

initial_point:
  split_cls: 8
  split_seg: 6

GP:
  lr: 0.1
  iterations: 3000
  verbose: False

method: gridmax
surface_interpolation:
  method: splines # splines, triangles
  degree: 3 # only for splines

gradient_descent:
  lr: 1000
  lr_step: 0.99
  n_epochs: 25000
  patience: 5  # times writing_schedule
  writing_schedule: 1000
  verbose: True

save_plots: True
surface_file: pascal_surface.txt